[phases.setup]
nixPkgs = ["python311", "texlive.combined.scheme-medium"]

[phases.install]
cmds = ["python -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = ". .venv/bin/activate && uvicorn app.main:create_app --host 0.0.0.0 --port $PORT --factory"
