[phases.setup]
nixPkgs = ["python311", "texlive.combined.scheme-medium"]
aptPkgs = ["texlive-latex-base", "texlive-latex-extra", "texlive-fonts-recommended", "texlive-fonts-extra", "latexmk"]

[phases.install]
cmds = ["python -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = ". .venv/bin/activate && uvicorn app.main:create_app --host 0.0.0.0 --port $PORT --factory"
